version: '3.8'

services:
  app:
    container_name: app
    image: 'backend-portfolio'
    build:
      context: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/test
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
  db:
    container_name: db
    image: mysql:8.0.31
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=secret
    command: --authentication_policy=mysql_native_password
    ports:
      - "3306:3306"
    restart: always