name: Gradle launcher

on:
  workflow_call:
    inputs:
      commands:
        default: 'build'
        required: false
        type: string

jobs:
  launcher:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradle build
        uses: gradle/gradle-build-action@v2.3.3
        with:
          gradle-version: wrapper
          arguments: ${{ inputs.commands }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}